### ISSUE TITLE
Unfair Mining Rewards

### ISSUE THREAD

**Issue by blockwhalex** [QuilibriumNetwork/ceremonyclient#241]
I was running two nodes in May, but one stopped after several days and its rewards(about 70 QUILs) keeps unchanged till today. Yet I am still running the other node, but no gains at all and its rewards is unreasonably taken back by over **50%**! Last time I checked the rewards was 1306 QUILs, and now it's only 620 QUILs left with the same peer id. So why not stop running from then on?! If this is a mistake, I hope your project will correct it ASAP, or I will report your scam bahavior to GitHub as well as GitLab.

Related peer id:
QmZgx5XeW6b1tj4usoqeThKEmv3YiBr2VbGiXhSAsQHxew
QmV9EMFadKRAwJBvp3kXo5gt6tproC8oBaX3CJcQhjMDSY

<img width="554" alt="螢幕截圖 2024-06-17 上午1 32 19" src="https://github.com/QuilibriumNetwork/ceremonyclient/assets/11309270/5d48eee3-d21a-403e-8ce1-d381db76dea0">

<img width="720" alt="螢幕截圖 2024-06-17 上午1 15 11" src="https://github.com/QuilibriumNetwork/ceremonyclient/assets/11309270/e0a719bc-0174-49c2-b60a-4b5bad9bcdfe">
<img width="720" alt="螢幕截圖 2024-06-17 上午1 15 36" src="https://github.com/QuilibriumNetwork/ceremonyclient/assets/11309270/1f8d65f5-026e-44d9-9136-87444b7855f9">

**Comment by CassOnMars** [comment]
There has been some confusion and miscommunication around the 1.4.18 rewards – the rewards on the Quilibrium website are the retroactive rewards, and were subject to change as we were battling discovery issues on the network. More peers were surfaced after reviewing the DHT logs, and due to messages being dropped due to poor performance on the part of gossipsub (which we are replacing), the rewards are a best faith effort approximation of the network. It's not ideal, we recognize that – retroactive rewards were done as a measure in the first place to address the fact that the network had been in an incentivized testnet mode. From 1.4.19 onward, rewards are accurately reflected locally on your node – specifically for all rewards moving on from 1.4.19. There are many folks who have been running for quite some time during our testnet phase that were already familiar with these revisions that had occurred previously. We are trying to resolve communication barriers, but we are a small team with no external VC funding at this time, and doing so is quite difficult.
