### ISSUE TITLE
Node keeps failing while starting with "invalid table" error

### ISSUE THREAD

**Issue by sercanCyberVision** [QuilibriumNetwork/ceremonyclient#79]
My node keeps failing while restarting with below error;

```
{"level":"info","ts":1709053362.2602189,"caller":"ceremony/ceremony_data_clock_consensus_engine.go:255","msg":"starting ceremony consensus engine"}
{"level":"info","ts":1709053362.2602262,"caller":"ceremony/ceremony_data_clock_consensus_engine.go:260","msg":"loading last seen state"}
{"level":"info","ts":1709053362.261019,"caller":"master/master_clock_consensus_engine.go:146","msg":"peers in store","peer_store_count":75,"network_peer_count":6}
panic: get latest data clock frame: pebble/table: invalid table 047146 (checksum mismatch at 0/14117670)

goroutine 360077 [running]:
source.quilibrium.com/quilibrium/monorepo/node/consensus/time.(*DataTimeReel).Start(0xc005cae000)
	/opt/ceremonyclient/node/consensus/time/data_time_reel.go:125 +0x2fd
source.quilibrium.com/quilibrium/monorepo/node/consensus/ceremony.(*CeremonyDataClockConsensusEngine).Start(0xc00002a000)
	/opt/ceremonyclient/node/consensus/ceremony/ceremony_data_clock_consensus_engine.go:261 +0x96
source.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).Start.func1()
	/opt/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:438 +0x33
created by source.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).Start
	/opt/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:437 +0x198
exit status 2
```

Any suggestion for this issue?

**Comment by sercanCyberVision** [comment]
When I was playing around, I have moved the corresponding file from the store to another location:
```
mv ./.config/store/047146.sst ./
```
As expected, I have received `file does not exist` error:
```
Loading ceremony state and starting node...
panic: L0: 047146: file 047146 (type 2) unknown to the objstorage provider: file does not exist

goroutine 1 [running]:
source.quilibrium.com/quilibrium/monorepo/node/store.NewPebbleDB(0xc000830090)
	/opt/ceremonyclient/node/store/pebble.go:17 +0x96
source.quilibrium.com/quilibrium/monorepo/node/app.NewNode(0xc0000b4f00)
	/opt/ceremonyclient/node/app/wire_gen.go:28 +0x65
main.main()
	/opt/ceremonyclient/node/main.go:160 +0x3bf
exit status 2
```

Once I have moved it back, the initial repetitive error has been gone, the node works now. I am not sure how this solved the issue.

**Comment by kawax0** [comment]
Hello, 

I'm encountering the same persistent issue with "checksum mismatch" error that's preventing my node from restarting properly. I tried the above described workaround but unfortunately, this hasn't worked in my case. 

Upon node restart, I'm faced with the following error:

`panic: get latest master clock frame: pebble/table: invalid table 001564 (checksum mismatch at 0/14107463)

goroutine 1 [running]:
source.quilibrium.com/quilibrium/monorepo/node/consensus/time.(*MasterTimeReel).Start(0xc001fb01b0)
	/root/kawaxo/quil/ceremonyclient/node/consensus/time/master_time_reel.go:78 +0x26d
source.quilibrium.com/quilibrium/monorepo/node/consensus/master.(*MasterClockConsensusEngine).Start(0xc001e26b40)
	/root/kawaxo/quil/ceremonyclient/node/consensus/master/master_clock_consensus_engine.go:126 +0x99
source.quilibrium.com/quilibrium/monorepo/node/app.(*Node).Start(0xc001fad2c0)
	/root/kawaxo/quil/ceremonyclient/node/app/node.go:52 +0x3f
main.main()
	/root/kawaxo/quil/ceremonyclient/node/main.go:187 +0x82c
exit status 2`


I'm hoping to find a solution to this issue or at least understand its root cause better. Any insights or suggestions from the community would be greatly appreciated.

Thank you for your time and assistance.

**Comment by CassOnMars** [comment]
if pebble is informing you that your table is irrecoverable, you will need to wipe the store:

```
rm -r .config/store/
```

In the long run, we plan to migrate from pebble to something in-house
